# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from src.proto import shikimori_pb2 as src_dot_proto_dot_shikimori__pb2


class AnimeCrawlerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetAnime = channel.unary_unary(
                '/AnimeCrawler/GetAnime',
                request_serializer=src_dot_proto_dot_shikimori__pb2.AnimeRequest.SerializeToString,
                response_deserializer=src_dot_proto_dot_shikimori__pb2.AnimeResponse.FromString,
                )
        self.GetStaff = channel.unary_unary(
                '/AnimeCrawler/GetStaff',
                request_serializer=src_dot_proto_dot_shikimori__pb2.StaffRequest.SerializeToString,
                response_deserializer=src_dot_proto_dot_shikimori__pb2.StaffResponse.FromString,
                )
        self.GetCharacters = channel.unary_unary(
                '/AnimeCrawler/GetCharacters',
                request_serializer=src_dot_proto_dot_shikimori__pb2.CharactersRequest.SerializeToString,
                response_deserializer=src_dot_proto_dot_shikimori__pb2.CharactersResponse.FromString,
                )
        self.GetStudio = channel.unary_unary(
                '/AnimeCrawler/GetStudio',
                request_serializer=src_dot_proto_dot_shikimori__pb2.StudioRequest.SerializeToString,
                response_deserializer=src_dot_proto_dot_shikimori__pb2.StudioResponse.FromString,
                )


class AnimeCrawlerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetAnime(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStaff(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCharacters(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStudio(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AnimeCrawlerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetAnime': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAnime,
                    request_deserializer=src_dot_proto_dot_shikimori__pb2.AnimeRequest.FromString,
                    response_serializer=src_dot_proto_dot_shikimori__pb2.AnimeResponse.SerializeToString,
            ),
            'GetStaff': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStaff,
                    request_deserializer=src_dot_proto_dot_shikimori__pb2.StaffRequest.FromString,
                    response_serializer=src_dot_proto_dot_shikimori__pb2.StaffResponse.SerializeToString,
            ),
            'GetCharacters': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCharacters,
                    request_deserializer=src_dot_proto_dot_shikimori__pb2.CharactersRequest.FromString,
                    response_serializer=src_dot_proto_dot_shikimori__pb2.CharactersResponse.SerializeToString,
            ),
            'GetStudio': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStudio,
                    request_deserializer=src_dot_proto_dot_shikimori__pb2.StudioRequest.FromString,
                    response_serializer=src_dot_proto_dot_shikimori__pb2.StudioResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'AnimeCrawler', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class AnimeCrawler(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetAnime(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/AnimeCrawler/GetAnime',
            src_dot_proto_dot_shikimori__pb2.AnimeRequest.SerializeToString,
            src_dot_proto_dot_shikimori__pb2.AnimeResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetStaff(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/AnimeCrawler/GetStaff',
            src_dot_proto_dot_shikimori__pb2.StaffRequest.SerializeToString,
            src_dot_proto_dot_shikimori__pb2.StaffResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetCharacters(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/AnimeCrawler/GetCharacters',
            src_dot_proto_dot_shikimori__pb2.CharactersRequest.SerializeToString,
            src_dot_proto_dot_shikimori__pb2.CharactersResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetStudio(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/AnimeCrawler/GetStudio',
            src_dot_proto_dot_shikimori__pb2.StudioRequest.SerializeToString,
            src_dot_proto_dot_shikimori__pb2.StudioResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
